import { Manrope } from 'next/font/google';

export const metadata = {
  title: 'the best histogramm in the world',
  description: 'generated by next.js',
};

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={manrope.className}>
      <body>{children}</body>
    </html>
  );
}
